name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Schedule to run every 6 hours
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Jekyll (or your static site generator)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site (Adjust if you use another build tool)
        run: |
          bundle exec jekyll build  # Modify if you use a different generator

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: './_site'  # Modify to the correct path for your build output

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_path: './_site'
