name: Update Shop Status

on:
  schedule:
    - cron: '0 */1 * * *'

  workflow_dispatch:
    # Allows you to trigger the run manually from the GitHub Actions tab

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests
          pip install pytz
          pip install beautifulsoup4
          pip install atproto

      - name: Run status script
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: python check_url.py

      - name: Commit and Push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add README.md
          # Only commit and push if the README.md file actually changed
          git diff --cached --quiet || (git commit -m "🛠️ Update shop statuses" && git push)
